// Mocks generated by Mockito 5.4.6 from annotations
// in jackedlog/test/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jackedlog/spotify/spotify_service.dart' as _i2;
import 'package:jackedlog/spotify/spotify_web_api_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spotify_sdk/models/player_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SpotifyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotifyService extends _i1.Mock implements _i2.SpotifyService {
  MockSpotifyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get hasValidToken => (super.noSuchMethod(
        Invocation.getter(#hasValidToken),
        returnValue: false,
      ) as bool);

  @override
  void restoreTokens({
    required String? accessToken,
    required DateTime? tokenExpiry,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #restoreTokens,
          [],
          {
            #accessToken: accessToken,
            #tokenExpiry: tokenExpiry,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<bool> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> togglePlayPause() => (super.noSuchMethod(
        Invocation.method(
          #togglePlayPause,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> skipNext() => (super.noSuchMethod(
        Invocation.method(
          #skipNext,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> skipPrevious() => (super.noSuchMethod(
        Invocation.method(
          #skipPrevious,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seekTo(int? positionMs) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [positionMs],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> toggleShuffle() => (super.noSuchMethod(
        Invocation.method(
          #toggleShuffle,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> toggleRepeat() => (super.noSuchMethod(
        Invocation.method(
          #toggleRepeat,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.PlayerState?> getPlayerState() => (super.noSuchMethod(
        Invocation.method(
          #getPlayerState,
          [],
        ),
        returnValue: _i3.Future<_i4.PlayerState?>.value(),
      ) as _i3.Future<_i4.PlayerState?>);

  @override
  _i3.Future<void> playTrack(String? spotifyUri) => (super.noSuchMethod(
        Invocation.method(
          #playTrack,
          [spotifyUri],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SpotifyWebApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotifyWebApiService extends _i1.Mock
    implements _i5.SpotifyWebApiService {
  MockSpotifyWebApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set accessToken(String? token) => super.noSuchMethod(
        Invocation.setter(
          #accessToken,
          token,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<List<Map<String, dynamic>>> getQueue() => (super.noSuchMethod(
        Invocation.method(
          #getQueue,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getRecentlyPlayed({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyPlayed,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, String>?> getPlaybackContext() => (super.noSuchMethod(
        Invocation.method(
          #getPlaybackContext,
          [],
        ),
        returnValue: _i3.Future<Map<String, String>?>.value(),
      ) as _i3.Future<Map<String, String>?>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
